### ISSUE TITLE
template a utiliser planificateur

### ISSUE THREAD

**Issue by bouchelm** [l3miage-bouchelm/Projet-Integrateur-L3MIAGE-G09#1]
Bonjour Mr,pour la partie planificateur pour faire la fonctionnalité planificateur : construire une journée il nous est demandé d'utiliser un formulaire, est ce qu'on doit quand méme du coup utiliser le template dans l'onglet lists ? pour la partie connexion est ce qu'on peut injecter la partie firebase sur un autre composant que racine (sur un composant connexion auquel fait référence dans la vue :       <a mat-list-item routerLink="/connexion" routerLinkActive="active">Connexion</a>  )

**Comment by AlexDmr** [comment]
Pour le formulaire, c'est une suggestion, vous pouvez faire comme vous voulez pour permettre au plannificateur de construire ou modifirer une journée.
Pour la partie Firebase, idem, vous pouvez aussi le demander à partir d'un autre composant que le composant racine.

**Comment by AlexDmr** [comment]
[ligne 64](https://github.com/l3-miage-cl-ihm/projet-integrateur-2024-amorce-technique-ihm-l3miage-severinm/blob/fee4806ee03ca397a033983a206b6c408475c54f/src/app/components/liste-livraisons/liste-livraisons.component.ts#L64) : Il faut bien utiliser la fonction polyline, pas le constructeur.

[ligne 72](https://github.com/l3-miage-cl-ihm/projet-integrateur-2024-amorce-technique-ihm-l3miage-severinm/blob/fee4806ee03ca397a033983a206b6c408475c54f/src/app/components/liste-livraisons/liste-livraisons.component.ts#L72) Vous avez un problème lorsque polyline est null -> Ne zapper pas le système de typage. ici vous pouvez plutôt utiliser un autyre typage qui fonctionne à tout les coups => un signal de Polyline[] => avec une valeur par défaut à [ ]
